import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from backend.tools.formatter import extract_multi_file_edits

raw = """Generated by local model provider.

body {
    margin: 0;
}
</file>

<file path="app.js" reason="Create an app.js file">
document.getElementById("travelForm").addEventListener("submit", function (e) {
});
</file>
"""

print(extract_multi_file_edits(raw))

