from __future__ import annotations

import logging

from backend.api.schemas import GenerateResponse, ValidationResult, WorkspaceEdit
from backend.agent.context_agent import RequestContext
from backend.agent.rag_controller import RagDecision
from backend.tools.diff_builder import build_unified_diff
from backend.tools.formatter import FormattedModelOutput, extract_code_and_explanation, extract_explanation_only

logger = logging.getLogger(__name__)


class ResponseFormatterAgent:
    def extract(self, raw_output: str, context: RequestContext) -> FormattedModelOutput:
        logger.debug("Raw model output before formatting for task=%s: %r", context.task, raw_output)
        if context.task == "project_explain":
            formatted = extract_explanation_only(raw_output)
        else:
            formatted = extract_code_and_explanation(raw_output, context.language)
        logger.debug("Cleaned/generated_code after post-processing for task=%s: %r", context.task, formatted.code)
        logger.debug("Extracted explanation for task=%s: %r", context.task, formatted.explanation)
        if raw_output.strip() and not formatted.code.strip() and context.task != "project_explain":
            logger.warning(
                "Formatter extracted empty code from non-empty raw model output for task=%s language=%s raw_output=%r",
                context.task,
                context.language,
                raw_output,
            )
        return formatted

    def format(
        self,
        raw_output: str,
        context: RequestContext,
        rag: RagDecision,
        validation: ValidationResult,
        stored: bool,
        metadata: dict[str, object] | None = None,
    ) -> GenerateResponse:
        formatted = self.extract(raw_output, context)
        generated = formatted.code
        explanation = formatted.explanation or "Generated by local model provider."
        
        import re
        edits = []
        # Support truncated XML by matching up to </workspace_edits> OR end of string
        workspace_match = re.search(r"<workspace_edits>(.*?)(?:</workspace_edits>|$)", raw_output, re.DOTALL | re.IGNORECASE)
        if workspace_match:
            edits_str = workspace_match.group(1)
            # Match individual edits, also tolerant of missing closing tags on the last edit
            edit_matches = re.finditer(r'<edit\s+file="([^"]+)">\s*<reason>(.*?)</reason>\s*<code>(.*?)(?:</code>|</edit>|$)', edits_str, re.DOTALL | re.IGNORECASE)
            for m in edit_matches:
                edits.append(WorkspaceEdit(file_path=m.group(1), reason=m.group(2).strip(), new_content=m.group(3).strip()))
            
            if edits:
                # Clean the explanation of the XML block
                explanation = re.sub(r"<workspace_edits>.*?(?:</workspace_edits>|$)", "", raw_output, flags=re.DOTALL | re.IGNORECASE).strip()
                generated = "" # Clear main generated code since it's a multi-file edit
                
        if formatted.is_empty and not edits:
            explanation = "The local model returned an empty response. No fallback code was generated."
        elif formatted.is_fallback and not edits:
            explanation = "Fallback-style output was rejected and was not stored."
            
        should_diff = context.task in {"bug_fix", "refactoring", "perf_opt"} or (context.task == "code_gen" and bool(context.code))
        diff = build_unified_diff(context.code, generated, context.file_path) if should_diff and context.code and generated else None
        
        return GenerateResponse(
            task=context.task,
            language=context.language,
            generated_code=generated,
            explanation=explanation,
            diff=diff,
            used_rag=rag.use_rag,
            rag_sources=rag.sources if rag.use_rag else [],
            validation=validation,
            edits=edits,
            metadata={
                "stored_in_memory": stored,
                "empty_model_output": formatted.is_empty,
                "fallback_output": formatted.is_fallback,
                "rag_best_score": rag.best_score,
                "rag_threshold": rag.threshold,
                "rag_skip_reason": rag.skip_reason,
                "validator_used": validation.validator,
                "validation_duration_ms": validation.duration_ms,
                "validation_errors": validation.errors,
                "validation_warnings": validation.warnings,
                **(metadata or {}),
            },
        )
